version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: skhanm/tibbway:latest
    ports:
      - "3000:80"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    restart: always